import { createClient } from '@supabase/supabase-js';

/**
 * SQL SCHEMA FOR SUPABASE
 * Run this code in your Supabase SQL Editor (found in the sidebar of your Supabase dashboard):
 * 
 * -- 1. Create the table
 * CREATE TABLE public.queries (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   name TEXT NOT NULL,
 *   email TEXT NOT NULL,
 *   message TEXT NOT NULL,
 *   created_at TIMESTAMPTZ DEFAULT now() NOT NULL
 * );
 * 
 * -- 2. Enable Row Level Security (RLS)
 * ALTER TABLE public.queries ENABLE ROW LEVEL SECURITY;
 * 
 * -- 3. Create a policy to allow anyone to submit messages via the contact form
 * CREATE POLICY "Allow public insert" ON public.queries
 * FOR INSERT WITH CHECK (true);
 * 
 * -- 4. Create a policy to allow you (authenticated dashboard user) to view submissions
 * CREATE POLICY "Allow authenticated select" ON public.queries
 * FOR SELECT USING (auth.role() = 'authenticated');
 */

const supabaseUrl = 'https://ghannvjxaukcscdrigla.supabase.co';
const supabaseAnonKey = 'sb_publishable_Cu52pO5vnBuit94yBWR2gA_azd5-Gw2';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);